﻿Produto novoproduto=new Produto();
System.Console.WriteLine(novoproduto.sep);
System.Console.WriteLine("Nome do produto");
novoproduto.nome=Console.ReadLine();
System.Console.WriteLine("Preço do produto");
novoproduto.preco=double.Parse(Console.ReadLine());
System.Console.WriteLine("Quantidade de unidades do produto");
novoproduto.unidade=int.Parse(Console.ReadLine());
System.Console.WriteLine(novoproduto.sep);
novoproduto.CalcularPreco();